name: SHCTF-2024-Scoreboard-ScreenShot

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  screenshot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get Time
        run: echo "datetime=$(date +'%Y-%m-%d-%H-%M')" >> $GITHUB_ENV

      - name: ScreenShot
        uses: swinton/screenshot-website@v1.x
        with:
          source: 'https://shc.tf/games/1/scoreboard'
          destination: 'screenshot-${{ env.datetime }}.png'
          width: 5000
          full-page: true 

      - name: Move Screenshot to scoreboard folder
        run: mv screenshot-${{ env.datetime }}.png scoreboard/

      - name: Commit and Push Screenshot
        run: |
          git add scoreboard/screenshot-${{ env.datetime }}.png
          git commit -m "Add screenshot-${{ env.datetime }}.png"
          git push origin main
