name: Playwright Screenshot

on:
  push:
    branches:
      - main

jobs:
  screenshot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Chinese Fonts
        run: |
          sudo apt-get update
          sudo apt-get install -y fonts-noto-cjk # 安装Noto CJK字体

      - name: Install Playwright
        run: npm install playwright

      - name: Run Playwright Script
        run: |
          npx playwright install
          node screenshot.js

      - name: List files in the workspace
        run: ls -alh

      - name: Get Time
        run: echo "datetime=$(date +'%Y-%m-%d-%H-%M')" >> $GITHUB_ENV

      # 继续后续步骤
      - name: Create output directory
        run: mkdir -p screenshots

      - name: Move Screenshot
        run: mv scoreboard_screenshot.png screenshots/screenshot-${{ env.datetime }}.png

      - name: Configure Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Checkout to scoreboard branch
        run: |
          git checkout -b scoreboard || git checkout scoreboard

      - name: Add files
        run: |
          git add screenshots/

      - name: Commit changes
        run: |
          git commit -m "Add screenshot taken at ${{ env.datetime }}"

      - name: Push changes
        run: |
          git push origin scoreboard
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
