name: SHCTF-2024-Scoreboard-ScreenShot

on:
  schedule:
    - cron: '0 * * * *'  # 每小时触发一次
  workflow_dispatch:

jobs:
  screenshot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get Time
        run: echo "datetime=$(date +'%Y-%m-%d-%H-%M')" >> $GITHUB_ENV

      - name: ScreenShot
        uses: swinton/screenshot-website@v1.x
        with:
          source: 'https://shc.tf/games/1/scoreboard'
          destination: 'screenshot-${{ env.datetime }}.png'
          width: 5000
          full-page: true

      # 创建一个目录来存放截图文件（这步可以根据实际需求调整）
      - name: Create output directory
        run: mkdir -p screenshots

      # 将截图移动到 output 目录中（方便后续提交操作）
      - name: Move Screenshot
        run: mv screenshot-${{ env.datetime }}.png screenshots/

      # 配置 Git 用户
      - name: Configure Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      # 创建或切换到 scoreboard 分支，并复制文件
      - name: Checkout to scoreboard branch
        run: |
          git checkout -b scoreboard || git checkout scoreboard

      # 将截图文件添加到 Git 暂存区
      - name: Add files
        run: |
          git add screenshots/

      # 提交到 scoreboard 分支
      - name: Commit changes
        run: |
          git commit -m "Add screenshot taken at ${{ env.datetime }}"

      # 推送到 scoreboard 分支
      - name: Push changes
        run: |
          git push origin scoreboard
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
