name: SHCTF-2024-Scoreboard-ScreenShot

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  screenshot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get Date
        id: get_date
        run: echo "date=$(date +'%m-%d')" >> $GITHUB_ENV

      - name: ScreenShot
        uses: swinton/screenshot-website@v1.x
        with:
          source: 'https://shc.tf/games/1/scoreboard'
          destination: 'screenshot-${{ env.date }}.png'
          width: 5000
          full-page: true 

      - name: Upload screenshot
        uses: actions/upload-artifact@v3
        with:
          name: scoreboard-screenshot-${{ env.date }}
          path: scoreboard/screenshot-${{ env.date }}.png
